Create an Issue Finder page on the sie
creativecommons/creativecommons.github.io-source pull request #502
Opened 2020-09-06 07:44 UTC by dhruvkb

## Description
This PR adds a new 'Issue Finder' page to the site.

## Screenshot
![2020-09-06 13 12 19 localhost 8f95021b0a61](https://user-images.githubusercontent.com/16580576/92320888-bf869f00-f042-11ea-8603-77a9c22aaffe.png)

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-09-06 07:46 UTC, dhruvkb commented
@kgodey apparently the GitHub API required [authentication](https://developer.github.com/v3/issues/#list-organization-issues-assigned-to-the-authenticated-user). Can we generate a read-only no-permissions token for use on the site?

2020-09-07 06:12 UTC, Dhruvi16 commented
This is awesome. @dhruvkb 👍🏼

2020-09-09 15:43 UTC, dhruvkb commented on webpack/js/issue-finder.js
> +  auth: ''
This is required.

2020-09-09 18:52 UTC, kgodey requested changes
@dhruvkb this is a great start! some high level feedback:
- please make the filters all on one line so that they don't take up the entire page – right now, you can't even see the issues unless you scroll. alternatively, use sidebar filters like CC Search
- let's remove the aspect filter, I don't see it getting a lot of use.
- I think we should change the experienced filter to "is this your first time contributing to CC" and then filter by "good first issue", a yes/no question is an easier choice.
- can we populate the skills based on the technologies used in the cc metadata file? it seems better than having skills/technologies in two different places (that isn't related to this PR exactly, so feel free to make a different issue for it)
- can we have background colors for the labels?

2020-09-10 13:25 UTC, dhruvkb commented
Updated screenshot:
![2020-09-10 18 53 27 localhost b32efca54dba](https://user-images.githubusercontent.com/16580576/92735454-0ce27380-f397-11ea-8ebe-63dab3b8127d.png)

2020-09-10 13:55 UTC, hugosolar approved these changes
This looks awesome, I think it will be very helpful, especially for internships. Great work @dhruvkb

2020-09-10 16:19 UTC, aldenstpage approved these changes

2020-09-10 16:32 UTC, kgodey requested changes
@dhruvkb this looks fantastic! a couple more small things:
- it looks like the filtering is happening instantly for skills, but the experience level requires pressing the search button. please standardize on one or the other and remove the search button if needed.
- please add some introductory text to the top of the page explaining that these are all issues that we are looking for help with, etc.
- please link to the issue finder from the contribution guidelines

2020-09-10 17:21 UTC, zackkrida requested changes
_Love_ the redesign. One suggestion—adding `placeholder="Any skills"` to the `#skills` VueSelect.

<img width="292" alt="Screen Shot 2020-09-10 at 7 20 41 AM" src="https://user-images.githubusercontent.com/6351754/92771036-420aa980-f336-11ea-80e6-b94e9faf7854.png">

2020-09-10 23:01 UTC, zackkrida approved these changes

2020-09-11 15:29 UTC, kgodey commented
@dhruvkb the changes look good! I'll re-review this after the new databag implementation.

2020-09-12 04:50 UTC, dhruvkb commented
Databag implementation creativecommons/ccos-scripts#79

2020-09-25 16:10 UTC, kgodey approved these changes

2020-09-25 16:13 UTC, merged