closes #159 Move information about old GSoC projects to CC Open Source
creativecommons/creativecommons.github.io-source pull request #576
Opened 2020-12-15 10:05 UTC by Cronus1007

## Fixes
Fixes #159 by @hugosolar 

## Description
Adds contents about the old gsoc projects to the website.
## Technical details

Just have added a lot of the `contents.lr` file in relation to close the PR.
## Tests
No Tests since my work is related a lot to Front End .
## Screenshots

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [] I added tests for the changes I made (if applicable).
- [] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.
## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-12-15 10:08 UTC, Cronus1007 commented
@dhruvkb Just a look how I am proceeding for this PR. So let me know the required changes.

2020-12-16 19:17 UTC, Cronus1007 commented
@dhruvkb @kgodey Getting information about the GSOC-08,07,06 has been very much difficult.

2020-12-20 12:20 UTC, Cronus1007 commented
@TimidRobot

2020-12-21 01:36 UTC, dhruvkb requested changes
1. Could use some improvements in terms of punctuation, spelling and grammar. I would recommend setting up [Grammarly](https://www.grammarly.com/) to help with that.
2. All the `md5_hashed_email` fields are identical. If you don't have the email addresses, it would be preferable to leave them blank rather than populate an arbitrary value.
3. Use the same value for the author `username` field as the name of the file, for consistency.
4. I would suggest using this template for the bio:

```txt
<full name> ([`@<github handle>`](<github profile link>) on GitHub) was a Google Summer of Code <year> intern with Creative Commons. They developed [<project name>](<project link>) as a part of their internship.
```

2020-12-21 01:36 UTC, dhruvkb commented on content/blog/authors/Ethan-Lim/contents.lr
> +Ethan-Lim was the Google Summer of Code Student in 2013 with Creative Commons as the mentor organization . Ethan developed `CC Media Fingerprinting Library` as part of [Google Summer of Code 2013](/g
```suggestion
Ethan-Lim was a Google Summer of Code intern with Creative Commons as the mentor organization. They developed `CC Media Fingerprinting Library` as part of [Google Summer of Code 2013](/gsoc-2013/).
```

2020-12-21 01:36 UTC, dhruvkb commented on content/blog/authors/Ishan-Thilina/contents.lr
> +
One newline should suffice.
```suggestion

```

2020-12-21 01:36 UTC, dhruvkb commented on content/blog/authors/Ishan-Thilina/contents.lr
> +Ishan Thilina
```suggestion
name: Ishan Thilina
```

2020-12-21 01:36 UTC, dhruvkb commented on content/blog/authors/THanish/contents.lr
> +[THanish](https://github.com/mnmtanish) was the Google Summer of Code Student with Creative Commons as the mentor organization. He goes by `@mmthanish` on the gitub Community. THanish developed [CC P
Their name is "Thanish" (with a lowecase "h").
```suggestion
[Thanish](https://github.com/mnmtanish) was the Google Summer of Code Student with Creative Commons as the mentor organization. He goes by `@mnmthanish` on the gitub Community. Thanish developed [CC Pasteboard](https://github.com/cc-archive/pasteboard) as part of [Google Summer of Code 2013](/gsoc-2013/).
```

2020-12-21 01:36 UTC, dhruvkb commented on content/blog/authors/akila/contents.lr
> +username: mmthanish
Please be careful.
```suggestion
username: akila
```

2020-12-21 04:40 UTC, Cronus1007 commented
@dhruvkb  But for few ones I am unable to find their github profile link. So shall I deleberately mark them as `#`

2021-01-06 17:07 UTC, Cronus1007 commented
@TimidRobot  Okk I will soon make the changes. Plzzzz review this PR as well #584

2021-01-14 16:52 UTC, Cronus1007 commented
@TimidRobot The source of the information is cc-archives and gsoc-wiki links given in the website. Yes there are many duplicated sentences which refers `Kriti` particularly as I found in blog posts of gsoc-2019 students.

2021-01-15 15:13 UTC, Cronus1007 commented
https://github.com/cc-archive/pasteboard
https://wiki.creativecommons.org/wiki/Summer_of_Code_2013
https://wiki.creativecommons.org/wiki/Summer_of_Code_2012

2021-02-20 19:03 UTC, merged